# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        # Minecraft only supports one version because GitHub wants it,
        # thank you very much (I don't understand how to get the index
        # of a matrix in the artifacts, thank you for understanding)
        java: [
          21,    # Current Java LTS & minimum supported by Minecraft
        ]
        # and run on both Linux, Windows and Mac
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: store reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            **/build/reports/
            **/build/test-results/
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' }} # Only upload artifacts built from one OS
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/